### ISSUE TITLE
Peer Code review

### ISSUE THREAD

**Issue by NelsonAraujo93** [flemton/todo-list-code-review#2]
Nelson: 
**Highlights: **
- Nice use of html tags.
- JS Code had best practices.
- WebpAck is well congifurated.
- Modules working good.

Gerson: 
**Highlights: **
- GitFlow correct
**Sugestions:**
- Try to keep all styles in one file.

**Comment by flemton** [comment]
@NelsonAraujo93 Thank you very much for sharing this, cheers 🥂
